INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (129.95,
'PMAG D-60 AR/M4',
'AR15/M4/M16',
null,
'MAG576',
'5.56x45mm NATO',
'60',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG576/MAG576-BLK-1.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG576/Single/MAG576-single-11-15.png&Format=jpg&background=ffffff&altFmImage_path=/Files/Files/Images/Products/noImage.png&Width=950&Height=450&Crop=5',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG576/Single/MAG576-single-2-15.png&Format=jpg&background=ffffff&altFmImage_path=/Files/Files/Images/Products/noImage.png&Width=950&Height=450&Crop=5',
null,
'black',
'Weight, w/Dust Cover: 20.5 oz.\$Weight, loaded (M855 NATO): 46 oz.\$Length, max: 7.4 in.\$Width, max: 4.1 in.',
'The PMAG D-60 is a durable, lightweight, highly reliable 60-round 5.56x45 NATO/.223 Remington* polymer drum magazine for AR15/M4 compatible weapons.
With a larger capacity than previous PMAGs, the PMAG D-60 gives the shooter 60 rounds of ammunition, effectively allowing the same round count as two standard capacity 30-round magazines without requiring a critical reload.\nThe unique drum configuration keeps the height of the magazine manageable as well as allowing for prone firing and easier storage. Features an easy-to-use loading lever, paint pen dot matrix for easy marking, and a rear window for instant capacity indication. Compatible with a wide range of NATO firearms such as the M4, M16, SCAR™ MK16/16S, HK®416, MR556, M27 IAR, IWI Tavor, and others',
'Next-generation impact and crush resistant polymer construction\$Wide compatibility with most "STANAG 4179" platforms such as the AR15, M4, M16, SCAR MK16/16S, HK416, MR556, M27 IAR, IWI Tavor, and others\$Will seat fully loaded on a closed bolt\$Bolt hold open feature to lock the bolt back on the last round\*\*\$Ratcheting Loading Lever to take tension off the spring for easy loading by hand\$Feed Tower compatible with most loading devices, including USGI stripper clips and guides, the StripLULA™, and others\$Designed to be left loaded for long term storage without any loss of function or degradation\$All components used are corrosion resistant\$Easy to disassemble for cleaning with only a flat-bladed screwdriver or similar\$Anti-glare translucent window on rear of drum allows for easy determination of rounds remaining\$Paint pen dot matrix panel on back of body to allow for identification marking\$Slip-on, semi-rigid Dust Cover prevents grit and debris intrusion during storage and transpor\$',
false,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG576/MAG576-HERO-3-15.png&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG576/MAG576-BLK-15.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')

INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (19.95,
'PMAG 40 AR/M4 GEN M3',
'AR15/M4/M16',
'GEN M3',
'MAG233',
'5.56x45mm NATO',
'40',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG233/MAG233-SND_BLK-2-15.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG233/single/MAG233-rifle-blk-15.png&Format=jpg&background=ffffff&altFmImage_path=/Files/Files/Images/Products/noImage.png&Width=950&Height=450&Crop=5',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG233/single/MAG233-rifle-snd-15.png&Format=jpg&background=ffffff&altFmImage_path=/Files/Files/Images/Products/noImage.png&Width=950&Height=450&Crop=5',
null,
'black',
null,
'The next-generation PMAG 40 GEN M3 is a 40-round 5.56x45 NATO (.223 Remington) polymer magazine for AR15/M4 compatible weapons. Along with expanded feature set and compatibility, the GEN M3 incorporates new material technology and manufacturing processes for enhanced strength, durability, and reliability to exceed rigorous military performance specifications.',
null,
false,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG233/MAG233-HERO-15.png&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG233/MAG233-blk-15.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')

INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (17.95,
'PMAG 30 AR/M4 GEN M3 WINDOW',
'AR15/M4/M16',
'GEN M3',
'MAG556',
'5.56x45mm NATO',
'30',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG556/MAG556-SND_BLK-2-15.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG556/Single/MAG556-single1-blk-15.png&Format=jpg&background=ffffff&altFmImage_path=/Files/Files/Images/Products/noImage.png&Width=950&Height=450&Crop=5',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG556/Single/MAG556-single2-blk-15.png&Format=jpg&background=ffffff&altFmImage_path=/Files/Files/Images/Products/noImage.png&Width=950&Height=450&Crop=5',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG556/Single/MAG556-single3-sand-15.png&Format=jpg&background=ffffff&altFmImage_path=/Files/Files/Images/Products/noImage.png&Width=950&Height=450&Crop=5',
'black',
null,
'The next-generation PMAG 30 GEN M3 Window is a 30-round 5.56x45 NATO (.223 Remington) polymer magazine for AR15/M4 compatible weapons that features transparent windows to allow rapid visual identification of approximate number of rounds remaining. Along with expanded feature set and compatibility, the GEN M3 Window incorporates new material technology and manufacturing processes for enhanced strength, durability, and reliability to exceed rigorous military performance specifications.',
null,
false,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG556/MAG556-HERO-15.png&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG556/MAG556-BLK-15.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')

INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (13.95,
'PMAG 10 AR/M4 GEN M3',
'AR15/M4/M16',
'GEN M3',
'MAG556',
'5.56x45mm NATO',
'10',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG559/MAG559-SND_BLK-2-15.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
null,
null,
null,
'black',
null,
null,
null,
false,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG559/MAG559-hero-1-15.png&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/AR_M4/MAG559/MAG559-blck-15.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')

INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (15.95,
'PMAG 17 GL9 -GLOCK G17',
'GLOCK',
'G17',
'MAG546',
'9x19MM Parabellum',
'17',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG546/MAG546-BLK-2.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
null,
null,
null,
'black',
null,
null,
null,
false,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG546/MAG546-HERO-15.png&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG546/MAG546-BLK-15.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')

INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (15.95,
'PMAG 15 GL9 -GLOCK G17',
'GLOCK',
'G17',
'MAG550',
'9x19MM Parabellum',
'15',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG550-PMAG15/MAG550_main.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
null,
null,
null,
'black',
null,
null,
null,
false,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG550-PMAG15/MAG550-HERO-15.png&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG550-PMAG15/MAG550-blk-15.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')

INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (19.95,
'PMAG 21 GL9 – GLOCK',
'GLOCK',
'GLOCK',
'MAG550',
'9x19MM Parabellum',
'21',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG661/MAG661-MAIN-2.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
null,
null,
null,
'black',
null,
null,
null,
true,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG661/MAG661-HERO-2.jpg&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG661/MAG661-Variant.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')

INSERT INTO products (price,name,platform,gen,modelNumber,caliber,capacity,category,subCategory,mainImg,imgOne,imgTwo,imgThree,color,specs,details,features,new,pageImg,detailImg)
VALUES (15.95,
'PMAG 12 GL9, 9x19 – GLOCK G26',
'GLOCK',
'G26',
'MAG674',
'9x19MM Parabellum',
'12',
'FIREARMS ACCESSORIES',
'PMAG Magazines',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG674-PMAG-12-GL9/MAG674PMAG12GL9Main.png&Width=360&Height=300&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=dfdfdf',
null,
null,
null,
'black',
null,
null,
null,
true,
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG674-PMAG-12-GL9/MAG674-PMAG_12_GL9Hero.jpg&Width=1270&Height=500&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff',
'https://www.magpul.com/Admin/Public/GetImage.ashx?Image=/Files/Files/Images/Products/Magazines/MAG674-PMAG-12-GL9/MAG674-PMAG-12-GL9Variant.png&Width=1200&Height=700&altFmImage_path=/Files/Files/Images/Products/noImage.png&Format=jpg&Crop=5&Background=ffffff')
